### ISSUE TITLE
The fetch window crashes all the time

### ISSUE THREAD

**Issue by micsova** [hapiest-team/hapiest#23]

**Comment by jkarns275** [comment]
Needs further testing to verify the issue is gone @micsova @BenjiCaro

**Comment by BenjiCaro** [comment]
@jkarns275 Was not solved by 97213672fb30f7ccb95aed997c9b0374ce46fdc6, resolved by 8e91e515e4a16dddf8e889d30840415a8a1ea055: the worker thread was being closed twice. Needs to be verified through testing

**Comment by jkarns275** [comment]
Whatever was causing these crashes has been fixed. Other bugs should have their own issue opened
