### ISSUE TITLE
Typing in a wavenum min and max is almost impossible

### ISSUE THREAD

**Issue by micsova** [hapiest-team/hapiest#24]
Instead of automatically changing the number if min > max, just add a marker (like a red X or squiggly line or something) if the values are invalid, then if the user tries to fetch with invalid values, instead of fetching, just tell them their values are invalid

**Comment by jkarns275** [comment]
This was fixed by 4c63a36f94b89d007a4d87cef604a9544983bec1 . The elements now allow any two numbers to be entered and, at the time of fetching, will swap the numbers if necessary.
