### ISSUE TITLE
Cannot graph tables that were created through 'select'

### ISSUE THREAD

**Issue by BenjiCaro** [hapiest-team/hapiest#25]
Upon trying to graph data that was put through select gives the following error:
[Err]  [Errno 2] No such file or directory: 'data/kyle.hmd'

hmd files are no longer necessary, there is no need to try and read the .hmd file anymore

**Comment by jkarns275** [comment]
The issue of the missing .hmd file has been fixed, however there still is issues when it comes to graphing data that has been created through select.

**Comment by jkarns275** [comment]
Fixed by 97213672fb30f7ccb95aed997c9b0374ce46fdc6
